
[tasks.install-tailwindcss]
condition = { files_not_exist = ["node_modules/.bin/tailwindcss"] }
command = "npm"
args = ["install", "-D", "tailwindcss@latest", "postcss@latest", "autoprefixer@latest"]

[tasks.compile-css]
command = "npx"
args = ["tailwindcss", "-i", "src/static/styles.css", "-o", "target/static/styles.css"]
dependencies = ["install-tailwindcss"]

[tasks.serve]
command = "trunk"
args = ["serve"]
dependencies = ["compile-css"]

[tasks.default]
run_task = "serve"

# serve watch
[tasks.sw]
command = "cargo"
args = ["watch", "--", "cargo", "make", "serve"]
